<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <Nullable>enable</Nullable>
    <ApplicationIcon />
    <StartupObject>SimpleTest.Program</StartupObject>

    <!-- Отключаем стандартный WinForms -->
    <UseWindowsForms>false</UseWindowsForms>
    <EnableWindowsTargeting>false</EnableWindowsTargeting>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <!-- Подключаем наш кастомный Windows.Forms -->
    <ProjectReference Include="..\System.Windows.Forms\System.Windows.Forms.csproj" />
  </ItemGroup>

</Project>