//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Forms.resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class System_Windows_Forms {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System_Windows_Forms() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("System.Windows.Forms.resources.System_Windows_Forms", typeof(System_Windows_Forms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        internal static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        internal static string _unknown_method_ {
            get {
                return ResourceManager.GetString("<unknown method>", resourceCulture);
            }
        }
        
        internal static string of__0_ {
            get {
                return ResourceManager.GetString("of {0}", resourceCulture);
            }
        }
        
        internal static string Move_first {
            get {
                return ResourceManager.GetString("Move first", resourceCulture);
            }
        }
        
        internal static string Move_previous {
            get {
                return ResourceManager.GetString("Move previous", resourceCulture);
            }
        }
        
        internal static string Current_position {
            get {
                return ResourceManager.GetString("Current position", resourceCulture);
            }
        }
        
        internal static string Total_number_of_items {
            get {
                return ResourceManager.GetString("Total number of items", resourceCulture);
            }
        }
        
        internal static string Move_next {
            get {
                return ResourceManager.GetString("Move next", resourceCulture);
            }
        }
        
        internal static string Move_last {
            get {
                return ResourceManager.GetString("Move last", resourceCulture);
            }
        }
        
        internal static string Add_new {
            get {
                return ResourceManager.GetString("Add new", resourceCulture);
            }
        }
        
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        internal static string Hue {
            get {
                return ResourceManager.GetString("Hue", resourceCulture);
            }
        }
        
        internal static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        internal static string Bri {
            get {
                return ResourceManager.GetString("Bri", resourceCulture);
            }
        }
        
        internal static string Define_Custom_Colors___ {
            get {
                return ResourceManager.GetString("Define Custom Colors >>", resourceCulture);
            }
        }
        
        internal static string Add_To_Custom_Colors {
            get {
                return ResourceManager.GetString("Add To Custom Colors", resourceCulture);
            }
        }
        
        internal static string Base_Colors {
            get {
                return ResourceManager.GetString("Base Colors", resourceCulture);
            }
        }
        
        internal static string User_Colors {
            get {
                return ResourceManager.GetString("User Colors", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        internal static string Categorized {
            get {
                return ResourceManager.GetString("Categorized", resourceCulture);
            }
        }
        
        internal static string Alphabetic {
            get {
                return ResourceManager.GetString("Alphabetic", resourceCulture);
            }
        }
        
        internal static string _Undo {
            get {
                return ResourceManager.GetString("&Undo", resourceCulture);
            }
        }
        
        internal static string Cu_t {
            get {
                return ResourceManager.GetString("Cu&t", resourceCulture);
            }
        }
        
        internal static string _Copy {
            get {
                return ResourceManager.GetString("&Copy", resourceCulture);
            }
        }
        
        internal static string _Paste {
            get {
                return ResourceManager.GetString("&Paste", resourceCulture);
            }
        }
        
        internal static string _Delete {
            get {
                return ResourceManager.GetString("&Delete", resourceCulture);
            }
        }
        
        internal static string Select__All {
            get {
                return ResourceManager.GetString("Select &All", resourceCulture);
            }
        }
        
        internal static string Enum_argument_value___0___is_not_valid_for_AutoCompleteMode {
            get {
                return ResourceManager.GetString("Enum argument value \'{0}\' is not valid for AutoCompleteMode", resourceCulture);
            }
        }
        
        internal static string Enum_argument_value___0___is_not_valid_for_AutoCompleteSource {
            get {
                return ResourceManager.GetString("Enum argument value \'{0}\' is not valid for AutoCompleteSource", resourceCulture);
            }
        }
        
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        internal static string Typing {
            get {
                return ResourceManager.GetString("Typing", resourceCulture);
            }
        }
        
        internal static string Font_Style_ {
            get {
                return ResourceManager.GetString("Font Style:", resourceCulture);
            }
        }
        
        internal static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        internal static string Font_ {
            get {
                return ResourceManager.GetString("Font:", resourceCulture);
            }
        }
        
        internal static string Effects {
            get {
                return ResourceManager.GetString("Effects", resourceCulture);
            }
        }
        
        internal static string Size_ {
            get {
                return ResourceManager.GetString("Size:", resourceCulture);
            }
        }
        
        internal static string Strikethrough {
            get {
                return ResourceManager.GetString("Strikethrough", resourceCulture);
            }
        }
        
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        internal static string Underlined {
            get {
                return ResourceManager.GetString("Underlined", resourceCulture);
            }
        }
        
        internal static string Script_ {
            get {
                return ResourceManager.GetString("Script:", resourceCulture);
            }
        }
    }
}
